import test, { expect } from "@playwright/test";
test.use({ headless: false })

test('Assignement 1 - Create Lead', async ({ page }) => {
    await page.goto('https://login.salesforce.com')
    await page.locator('[name=username]').fill('vidyar@testleaf.com')
    await page.fill('#password', 'Sales@123')
    await page.locator('#Login').click()
    await page.waitForTimeout(5000)
    await page.locator('.slds-icon-waffle').click()
    await page.waitForTimeout(2000)
    await page.locator('[aria-label="View All Applications"]').click()
    await page.waitForTimeout(2000)
    await page.locator('//p[contains(@class,"slds-truncate") and text()="Sales"]').click()
    await page.locator('//span[contains(@class,"slds-truncate") and text()="Leads"]').click()
    await page.locator('li > a > div[title="New"]').click()
    await page.locator('button[name="salutation"]').click()
    await page.locator('//div[@aria-label="Salutation"]/lightning-base-combobox-item[@data-value="Ms."]').click()
    await page.locator('input[name="firstName"]').fill('Christina')
    await page.locator('input[name="lastName"]').fill('Charles')
    await page.locator('input[name="Company"]').fill('CSOD')
    await page.locator('button[name="SaveEdit"]').click()
    await page.waitForTimeout(2000)
    expect(page.locator('slot lightning-formatted-name')).toHaveText('Ms. Christina Charles')
})

test('Assignment: 2 Edit Lead', async ({ page }) => {
    await page.goto('http://leaftaps.com/opentaps/control/main')
    await page.locator('//input[@id="username"]').fill('democsr2')
    await page.locator('//input[@name="PASSWORD"]').fill('crmsfa')
    await page.locator('//input[@class="decorativeSubmit"]').click()
    await page.waitForTimeout(3000)
    await page.locator('//a[contains(text(),"CRM/SFA")]').click()
    await page.locator('//a[text()="Leads"]').click()
    await page.locator('//a[text()="Create Lead"]').click()
    await page.waitForTimeout(3000)
    await page.locator('#createLeadForm_companyName').fill('CSOD')
    await page.locator('#createLeadForm_firstName').fill('Christina')
    await page.locator('#createLeadForm_lastName').fill('Charles')
    await page.locator('input[name="submitButton"]').click()
    await page.waitForTimeout(3000)
    await page.locator('//a[@class="subMenuButton" and text()="Edit"]').click()
    await page.locator('#updateLeadForm_companyName').fill('Cornerstone OnDemand')
    await page.locator('input[value="Update"]').click()
})

test.only('Assignment: 3 Create Individuals', async ({ page }) => {
    await page.goto('https://login.salesforce.com')
    await page.locator('[name=username]').fill('vidyar@testleaf.com')
    await page.fill('#password', 'Sales@123')
    await page.locator('#Login').click()
    await page.waitForTimeout(5000)
    await page.locator('.slds-icon-waffle').click()
    await page.waitForTimeout(2000)
    await page.locator('[aria-label="View All Applications"]').click()
    await page.waitForTimeout(2000)
    await page.locator('//p[text()="Individuals"]').click()
    await page.locator('//div[@title="New"]').click()
    await page.locator('//input[@placeholder="Last Name"]').fill('Charles')
    await page.locator('//button[@title="Save"]').click()
    await page.waitForTimeout(2000)
    expect(page.locator('div.slds-page-header__title span')).toHaveText('Charles')
})

test.only('Assignment: 4 Edit Individuals', async ({ page }) => {
    await page.goto('https://login.salesforce.com')
    await page.locator('[name=username]').fill('vidyar@testleaf.com')
    await page.fill('#password', 'Sales@123')
    await page.locator('#Login').click()
    await page.waitForTimeout(5000)
    await page.locator('.slds-icon-waffle').click()
    await page.waitForTimeout(2000)
    await page.locator('[aria-label="View All Applications"]').click()
    await page.waitForTimeout(2000)
    await page.locator('//p[text()="Individuals"]').click()
    await page.locator('//slot/span[text()="Charles"]/ancestor::tr/td').last().click()
    await page.locator('//div[contains(@class,"branding-actions")]//div[@title="Edit"]').click()
    await page.locator('//input[@placeholder="First Name"]').fill('Christina')
    await page.locator('div.salutation a').click()
    await page.locator('//a[@title="Ms."]').click()
    await page.locator('//button[@title="Save"]').click()
})